/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomToggleButton {
        /**
          * isOn is is-on in custom-toggle-button
         */
        "isOn": boolean;
    }
    interface TabulatorDemo {
    }
    interface WarningIcon {
    }
}
declare global {
    interface HTMLCustomToggleButtonElement extends Components.CustomToggleButton, HTMLStencilElement {
    }
    var HTMLCustomToggleButtonElement: {
        prototype: HTMLCustomToggleButtonElement;
        new (): HTMLCustomToggleButtonElement;
    };
    interface HTMLTabulatorDemoElement extends Components.TabulatorDemo, HTMLStencilElement {
    }
    var HTMLTabulatorDemoElement: {
        prototype: HTMLTabulatorDemoElement;
        new (): HTMLTabulatorDemoElement;
    };
    interface HTMLWarningIconElement extends Components.WarningIcon, HTMLStencilElement {
    }
    var HTMLWarningIconElement: {
        prototype: HTMLWarningIconElement;
        new (): HTMLWarningIconElement;
    };
    interface HTMLElementTagNameMap {
        "custom-toggle-button": HTMLCustomToggleButtonElement;
        "tabulator-demo": HTMLTabulatorDemoElement;
        "warning-icon": HTMLWarningIconElement;
    }
}
declare namespace LocalJSX {
    interface CustomToggleButton {
        /**
          * isOn is is-on in custom-toggle-button
         */
        "isOn"?: boolean;
        /**
          * This event will emit a isOn value
         */
        "onToggleEvent"?: (event: CustomEvent<boolean>) => void;
    }
    interface TabulatorDemo {
    }
    interface WarningIcon {
    }
    interface IntrinsicElements {
        "custom-toggle-button": CustomToggleButton;
        "tabulator-demo": TabulatorDemo;
        "warning-icon": WarningIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-toggle-button": LocalJSX.CustomToggleButton & JSXBase.HTMLAttributes<HTMLCustomToggleButtonElement>;
            "tabulator-demo": LocalJSX.TabulatorDemo & JSXBase.HTMLAttributes<HTMLTabulatorDemoElement>;
            "warning-icon": LocalJSX.WarningIcon & JSXBase.HTMLAttributes<HTMLWarningIconElement>;
        }
    }
}
