/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomDropdown {
        /**
          * array for country list
         */
        "countries": string[];
        /**
          * internalmodification of countryName
         */
        "countryInp": string;
        /**
          * it gets data from the tag
         */
        "countryName": string;
    }
    interface CustomToggleButton {
        /**
          * isOn is is-on in custom-toggle-button
         */
        "isOn": boolean;
    }
    interface WarningIcon {
    }
}
declare global {
    interface HTMLCustomDropdownElement extends Components.CustomDropdown, HTMLStencilElement {
    }
    var HTMLCustomDropdownElement: {
        prototype: HTMLCustomDropdownElement;
        new (): HTMLCustomDropdownElement;
    };
    interface HTMLCustomToggleButtonElement extends Components.CustomToggleButton, HTMLStencilElement {
    }
    var HTMLCustomToggleButtonElement: {
        prototype: HTMLCustomToggleButtonElement;
        new (): HTMLCustomToggleButtonElement;
    };
    interface HTMLWarningIconElement extends Components.WarningIcon, HTMLStencilElement {
    }
    var HTMLWarningIconElement: {
        prototype: HTMLWarningIconElement;
        new (): HTMLWarningIconElement;
    };
    interface HTMLElementTagNameMap {
        "custom-dropdown": HTMLCustomDropdownElement;
        "custom-toggle-button": HTMLCustomToggleButtonElement;
        "warning-icon": HTMLWarningIconElement;
    }
}
declare namespace LocalJSX {
    interface CustomDropdown {
        /**
          * array for country list
         */
        "countries"?: string[];
        /**
          * internalmodification of countryName
         */
        "countryInp"?: string;
        /**
          * it gets data from the tag
         */
        "countryName"?: string;
        /**
          * Emits country value
         */
        "onEmitCountryValue"?: (event: CustomEvent<string>) => void;
    }
    interface CustomToggleButton {
        /**
          * isOn is is-on in custom-toggle-button
         */
        "isOn"?: boolean;
        /**
          * This event will emit a isOn value
         */
        "onToggleEvent"?: (event: CustomEvent<boolean>) => void;
    }
    interface WarningIcon {
    }
    interface IntrinsicElements {
        "custom-dropdown": CustomDropdown;
        "custom-toggle-button": CustomToggleButton;
        "warning-icon": WarningIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-dropdown": LocalJSX.CustomDropdown & JSXBase.HTMLAttributes<HTMLCustomDropdownElement>;
            "custom-toggle-button": LocalJSX.CustomToggleButton & JSXBase.HTMLAttributes<HTMLCustomToggleButtonElement>;
            "warning-icon": LocalJSX.WarningIcon & JSXBase.HTMLAttributes<HTMLWarningIconElement>;
        }
    }
}
